[project]
name = "mission-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "BLASCOJ24", email = "j.blasco69@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "sentence-transformers>=6.1.0",
    "tiktoken>=0.14.0",
    "xgboost>=3.4.1",
]

[project.scripts]
mission-1 = "app:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "nbclient>=0.11.0",
    "nbconvert>=7.17.1",
    "nbformat>=5.11.1",
    "pandas>=3.0.6",
]
